import React from 'react';
import '../index.css';

export default class Editor extends React.Component {
    render() {
      return (
        <section id="main" className="editor">
            <h1>Main Part -- Editor</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam commodo lorem ac lorem aliquam molestie. Pellentesque aliquam, est vel efficitur vestibulum, tellus enim tempus mi, ut luctus neque felis eget lectus. Integer eget fringilla ante, et dignissim elit. Etiam rutrum nisi vel odio fermentum, eu mollis leo luctus. Mauris dapibus nisi ac mauris vestibulum, vitae ornare erat efficitur. Nulla blandit tincidunt lacus. Nulla viverra suscipit arcu a bibendum. Aliquam risus erat, scelerisque at auctor eget, bibendum sit amet elit. Morbi quis sapien volutpat, consectetur metus vitae, interdum nisl. Phasellus auctor eu leo ac efficitur. Pellentesque euismod eget ligula ut imperdiet. Vestibulum venenatis justo quis sem accumsan, ut fermentum lacus commodo.</p>
            <p>Nullam iaculis ipsum urna, vitae hendrerit erat rutrum id. Nulla aliquam scelerisque consequat. Ut nec ex ac mi dapibus sollicitudin. Vestibulum efficitur euismod venenatis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus vulputate augue at tellus pretium elementum eu fringilla mi. Aenean in nisl aliquet, suscipit velit non, luctus lectus. Pellentesque sit amet leo eu nisl egestas viverra at nec metus. Donec quis dictum risus. Donec imperdiet vitae neque at euismod. Nulla dapibus sapien nunc, eu rhoncus tellus dapibus ut. Nullam lectus dui, ornare quis ex eget, pulvinar posuere nulla. Morbi egestas eu lorem pulvinar rhoncus.</p>
            <p>Nam pulvinar velit vestibulum, tincidunt lorem eu, varius urna. Nullam elementum nec velit eu cursus. Ut interdum massa vel aliquam rhoncus. Pellentesque fringilla in leo sit amet hendrerit. Etiam pretium urna ac luctus tristique. Suspendisse non nisi cursus, hendrerit dui vel, consequat purus. Cras eu efficitur urna, sit amet ultricies augue. Pellentesque consectetur magna ex, a bibendum massa iaculis et. Praesent bibendum pellentesque pharetra. Nam sagittis, diam eget faucibus viverra, dui nibh consectetur libero, eget fringilla ante lacus sed tellus. Cras tincidunt eros at blandit rhoncus. Pellentesque eu ex id odio molestie molestie. Ut a leo tortor.</p>
            <p>Mauris malesuada quam a malesuada fermentum. Aenean consectetur vulputate dolor, non tempor lectus. Integer non cursus mi. Sed eget lorem lectus. Proin fringilla blandit eros, non consequat nulla ultrices ut. Sed ornare ut leo sed luctus. Nullam volutpat consectetur ante, vitae hendrerit eros semper nec. Nullam eget tellus est. Etiam in laoreet lorem. Quisque orci neque, placerat sed felis sit amet, pellentesque vulputate odio. Fusce id ipsum vestibulum neque mattis ultrices. Curabitur laoreet ac magna vitae ultrices. Cras facilisis porta egestas. Cras ac tristique mi. Sed felis nisi, consectetur ut ante eget, convallis lobortis risus. Praesent sagittis tellus et augue cursus, tincidunt luctus massa hendrerit.</p>
            <p>Phasellus sed turpis congue, mattis purus sed, volutpat ex. Maecenas eu egestas ex, hendrerit posuere ante. Ut dictum varius risus, eget dignissim erat. Sed sagittis ipsum quis mauris rhoncus, a porta lorem tincidunt. Etiam eu velit ac dui varius suscipit at at dui. Fusce risus turpis, aliquet aliquet metus a, ultrices efficitur lorem. Aenean sapien augue, ultrices nec ex ac, efficitur accumsan enim. Ut tellus dolor, mollis non neque quis, faucibus pulvinar diam. Aenean in ultricies diam, id consectetur velit. Proin posuere arcu in mauris pellentesque, tincidunt bibendum libero commodo. Duis maximus volutpat risus, a fermentum massa cursus vel. Etiam eleifend purus id suscipit faucibus. Sed convallis massa metus, et consectetur nisi laoreet vel.</p>
        </section>
      );
    }
}