import React from 'react';
import '../index.css';

export default class Side extends React.Component {
    render() {
      return (
        <section className="sidebar" id="side">
            <h1>Side Bar for future use.</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam commodo lorem ac lorem aliquam molestie. Pellentesque aliquam, est vel efficitur vestibulum, tellus enim tempus mi, ut luctus neque felis eget lectus. Integer eget fringilla ante, et dignissim elit. Etiam rutrum nisi vel odio fermentum, eu mollis leo luctus. Mauris dapibus nisi ac mauris vestibulum, vitae ornare erat efficitur. Nulla blandit tincidunt lacus. Nulla viverra suscipit arcu a bibendum. Aliquam risus erat, scelerisque at auctor eget, bibendum sit amet elit. Morbi quis sapien volutpat, consectetur metus vitae, interdum nisl. Phasellus auctor eu leo ac efficitur. Pellentesque euismod eget ligula ut imperdiet. Vestibulum venenatis justo quis sem accumsan, ut fermentum lacus commodo.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam commodo lorem ac lorem aliquam molestie. Pellentesque aliquam, est vel efficitur vestibulum, tellus enim tempus mi, ut luctus neque felis eget lectus. Integer eget fringilla ante, et dignissim elit. Etiam rutrum nisi vel odio fermentum, eu mollis leo luctus. Mauris dapibus nisi ac mauris vestibulum, vitae ornare erat efficitur. Nulla blandit tincidunt lacus. Nulla viverra suscipit arcu a bibendum. Aliquam risus erat, scelerisque at auctor eget, bibendum sit amet elit. Morbi quis sapien volutpat, consectetur metus vitae, interdum nisl. Phasellus auctor eu leo ac efficitur. Pellentesque euismod eget ligula ut imperdiet. Vestibulum venenatis justo quis sem accumsan, ut fermentum lacus commodo.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam commodo lorem ac lorem aliquam molestie. Pellentesque aliquam, est vel efficitur vestibulum, tellus enim tempus mi, ut luctus neque felis eget lectus. Integer eget fringilla ante, et dignissim elit. Etiam rutrum nisi vel odio fermentum, eu mollis leo luctus. Mauris dapibus nisi ac mauris vestibulum, vitae ornare erat efficitur. Nulla blandit tincidunt lacus. Nulla viverra suscipit arcu a bibendum. Aliquam risus erat, scelerisque at auctor eget, bibendum sit amet elit. Morbi quis sapien volutpat, consectetur metus vitae, interdum nisl. Phasellus auctor eu leo ac efficitur. Pellentesque euismod eget ligula ut imperdiet. Vestibulum venenatis justo quis sem accumsan, ut fermentum lacus commodo.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam commodo lorem ac lorem aliquam molestie. Pellentesque aliquam, est vel efficitur vestibulum, tellus enim tempus mi, ut luctus neque felis eget lectus. Integer eget fringilla ante, et dignissim elit. Etiam rutrum nisi vel odio fermentum, eu mollis leo luctus. Mauris dapibus nisi ac mauris vestibulum, vitae ornare erat efficitur. Nulla blandit tincidunt lacus. Nulla viverra suscipit arcu a bibendum. Aliquam risus erat, scelerisque at auctor eget, bibendum sit amet elit. Morbi quis sapien volutpat, consectetur metus vitae, interdum nisl. Phasellus auctor eu leo ac efficitur. Pellentesque euismod eget ligula ut imperdiet. Vestibulum venenatis justo quis sem accumsan, ut fermentum lacus commodo.</p>
        </section>
      );
    }
}
